require("plugin.configs.web-dev-icons") -- load this file before every plugin to make svgs work
require("plugin.configs.cmp")
require("plugin.configs.lsp")
require("plugin.configs.lspsaga")
require("plugin.configs.treesitter")
require("plugin.configs.telescope")
require("plugin.configs.bufferline")
require("plugin.configs.comment")
require("plugin.configs.git-sign")
require("plugin.configs.lualine")
require("plugin.configs.indent-line")
require("plugin.configs.luasnip")
require("plugin.configs.null-ls")
require("plugin.configs.nvim-colorizer")
require("plugin.configs.nvim-tree")
