-- require("plugin.configs.telescope")
-- require("plugin.configs.treesitter")
require("plugin.configs.nvim-tree")
require("plugin.configs.lsp")
require("plugin.configs.cmp")
require("plugin.configs.luasnip")
require("plugin.configs.null-ls")
-- require("plugin.configs.lualine")
-- require("plugin.configs.bufferline")
-- require("plugin.configs.indent-line")
-- require("plugin.configs.git-sign")
require("plugin.configs.nvim-colorizer")
require("plugin.configs.comment")
require("plugin.configs.leap")
require("fidget").setup({})
require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
local hop = require("hop")
vim.keymap.set("n", "s", function() hop.hint_char1({ current_line_only = false }) end, { remap = true })
vim.keymap.set("n", "S", function() hop.hint_char1({ current_line_only = false, hint_offset = -1 }) end, { remap = true })
