#!/bin/zsh

alias gb="cd .."
alias gh="cd ~/"
alias fzd="cd \$(find * -type d | fzf)"
alias exa="exa -all"
alias lf="lfrun"
alias lg="lazygit"
alias vi="nvim"
# for my dotfiles
alias myzsh="nvim ~/.zshrc"
alias myvi="cd ~/.config/nvim && vi"
alias prd="pnpm run dev"
alias avi="nvim -u ~/.config/astronvim/entry.lua"
# for tmux
alias tks="tmux kill-server"
alias tl="tmux ls"
alias ta="tmux a"
alias nixq="nix-env -q"
